theme: jekyll-theme-minimal
title: Burak Bayrakdar
description: Constantinopolitan in Edo <img class="emoji" style="vertical-align:middle;" alt="jp" height="20" width="20" src="/assets/img/jp.png">
logo: /assets/img/logo.png
favicon: /assets/img/favicon.ico
show_downloads: false

socialmedia:
  stackoverflow: 
    profile: https://stackoverflow.com/users/3641067/buræquete?tab=profile
    flair: https://stackexchange.com/users/flair/4475914.png?theme=clean
  linkedin: https://www.linkedin.com/in/bur%C3%A6quete/
  facebook: https://www.facebook.com/buraequete
  twitter: https://twitter.com/buraequete
  instagram: https://www.instagram.com/buraequete_
  youtube: https://www.youtube.com/c/buræquete
  spotify: https://open.spotify.com/user/w35zp8n0btspberptb0i06wiv
  steam: https://steamcommunity.com/id/buraequete/
  projecteuler: https://projecteuler.net/profile/buraequete.png
